In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from geopy import geocoders  
gn = geocoders.GeoNames(username="sebasg")
import geopy.distance
import cartopy.crs as ccrs

In [62]:
#import json w requests
materials_url = 'https://raw.githubusercontent.com/TransparencyToolkit/dataspec-sii/master/sii_data/material_data/materials.json'
materials_resp = requests.get(url=materials_url)
materials_data = materials_resp.json()

In [63]:
#convert json to pd dataframe
materials_df = pd.json_normalize(materials_data)
materials_df.head(3)

,bibtex_key,bibtex_type,category,company_name,date_added,date_modified,doc_cloud_id,document_title,found_in,hardware_software,...,support_or_customer_service,training,document_mentions,author,documen_title,bdsk_url_1,spy_files_release_volume,doc_cloud_container,parent_product,type_of_material
0,SAS-Institute-Inc_Customer-Success-Stories_Pro...,Document,"[Counter-Surveillance, Monitoring Centre, Anal...",SAS Institute Inc,[2014-07-08 12:15:57 +0000],[2014-07-08 12:20:22 +0000],[1215575-1290-sas-institue-inc-product-descrip...,[Customer Success Stories],"[United Kingdom, United States of America, Sou...",[Hardware/Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Oxygen-Forensics_Oxygen-Forensic-Suite_Brochure,Document,[Analysis],Oxygen Forensics,[2014-07-08 12:12:55 +0000],[2014-07-08 12:14:42 +0000],[1215576-1291-oxygen-forensics-brochure-oxygen...,[Oxygen Forensic Suite 2013],NaN,[Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Oxygen-Forensics_Oxygen-Forensic-Suite_Brochur...,Document,[Analysis],Oxygen Forensics,[2014-07-08 12:08:59 +0000],[2014-07-08 12:15:25 +0000],[1215591-1292-oxygen-forensics-brochure-oxygen...,[Oxygen Forensic Suite 2013],NaN,[Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
#import json w requests
companies_url = 'https://raw.githubusercontent.com/TransparencyToolkit/dataspec-sii/master/sii_data/company_data/companies.json'
companies_resp = requests.get(url=companies_url)
companies_data = companies_resp.json()

In [65]:
#convert json to pd dataframe
companies_df = pd.json_normalize(companies_data)
companies_df.head(3)

,bibtex_key,bibtex_type,address,address_line_1,address_line_2,address_line_3,address_line_4,address_line_5,company_name,date_added,...,bdsk_file_37,bdsk_file_38,bdsk_file_39,bdsk_file_40,bdsk_file_41,bdsk_file_42,bdsk_file_43,bdsk_file_44,bdsk_file_45,bdsk_file_46
0,Varus-Tecnologia,Company,Via Blvd. Atlixc\'ayotl No. 5208<br />Tower JV...,[Via Blvd. Atlixc\'ayotl No. 5208],[Tower JV III],[Col. San Martinito],[San Andres Cholula],[Puebla],Varus Tecnologia,[2016-04-15 16:03:28 +0000],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Magor-Corp,Company,Suite 100<br />350 Terry Fox Drive<br />Ottawa...,[Suite 100],[350 Terry Fox Drive],[Ottawa],[ON],[K2K 2W5],Magor Corp,[2016-04-07 13:45:59 +0000],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Reach-U,Company,Riia 24<br />Tartu<br />51010<br />Estonia<br />,[Riia 24],[Tartu],[51010],[Estonia],NaN,Reach-U,[2016-04-03 09:58:33 +0000],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
companies_df.shape

(526, 117)

In [67]:
materials_df.shape

(1359, 35)

In [68]:
companies_df.columns

Index(['bibtex_key', 'bibtex_type', 'address', 'address_line_1',
       'address_line_2', 'address_line_3', 'address_line_4', 'address_line_5',
       'company_name', 'date_added',
       ...
       'bdsk_file_37', 'bdsk_file_38', 'bdsk_file_39', 'bdsk_file_40',
       'bdsk_file_41', 'bdsk_file_42', 'bdsk_file_43', 'bdsk_file_44',
       'bdsk_file_45', 'bdsk_file_46'],
      dtype='object', length=117)

In [69]:
len(materials_df.columns)

35

In [70]:
print(companies_df.columns.values)

['bibtex_key' 'bibtex_type' 'address' 'address_line_1' 'address_line_2'
 'address_line_3' 'address_line_4' 'address_line_5' 'company_name'
 'date_added' 'date_modified' 'hq_city' 'offices_in' 'technology_sold'
 'website' 'description' 'company_documents' 'company_sales'
 'incorporation_date' 'news_1' 'news' 'ceo' 'defense_contractor' 'eu'
 'founder' 'hq_country' 'nato' 'oecd' 'wassenaar' 'found_in'
 'parent_company' 'news_2' 'email' 'incorperation_date' 'company_number'
 'telephone' 'address_line_6' 'released' 'bdsk_file_1' 'doccloudembeds'
 'highlighted_company' 'bdsk_file_2' 'public_private' 'twitter_handle'
 'address_2' 'address_2_line_1' 'address_2_line_2' 'address_2_line_3'
 'bdsk_file_3' 'other_known_trading_names' 'bdsk_file_4' 'bdsk_file_5'
 'bdsk_file_6' 'address_2_line_4' 'address_2_line_5' 'bdsk_file_7'
 'bdsk_file_8' 'bdsk_file_9' 'bdsk_file_10' 'previous_address' 'read'
 'address_line_7' 'address_2_line_6' 'withheld' 'bdsk_file_11'
 'bdsk_file_12' 'bdsk_file_13' 'bdsk_file_14' 'date_purchased_by_parent'
 'csr' 'location' 'trade_show' 'blog_1' 'blog_2' 'blog_3' 'blog_4'
 'bdsk_file_15' 'bdsk_file_16' 'bdsk_file_17' 'bdsk_file_18'
 'bdsk_file_19' 'bdsk_file_20' 'bdsk_file_21' 'bdsk_file_22' 'hq_2_city'
 'hq_2_country' 'news_3' 'news_4' 'ceo2' 'bdsk_file_23' 'bdsk_file_24'
 'bdsk_file_25' 'bdsk_file_26' 'bdsk_file_27' 'blog_5' 'blog_6' 'news_5'
 'news_6' 'bdsk_file_28' 'bdsk_file_29' 'bdsk_file_30' 'bdsk_file_31'
 'bdsk_file_32' 'bdsk_file_33' 'bdsk_file_34' 'bdsk_file_35'
 'bdsk_file_36' 'bdsk_file_37' 'bdsk_file_38' 'bdsk_file_39'
 'bdsk_file_40' 'bdsk_file_41' 'bdsk_file_42' 'bdsk_file_43'
 'bdsk_file_44' 'bdsk_file_45' 'bdsk_file_46']

In [71]:
companies_df = companies_df.drop(columns=[f"bdsk_file_{i}" for i in range(1,47)])
companies_df = companies_df.drop(columns=[f"address_line_{i}" for i in range(1,8)])
companies_df = companies_df.drop(columns=[f"address_2_line_{i}" for i in range(1,7)])
companies_df = companies_df.drop(columns=[f"blog_{i}" for i in range(1,7)])
companies_df = companies_df.drop(columns=[f"news_{i}" for i in range(1,7)])
companies_df = companies_df.drop(columns=["bibtex_type",
                                          "address",
                                          "date_added",
                                          "date_modified",
                                          "website",
                                          "incorperation_date",
                                          "released",
                                          "doccloudembeds",
                                          "highlighted_company",
                                          "previous_address",
                                          "read",
                                          "withheld",
                                          "date_purchased_by_parent",
                                          "location",
                                          "trade_show",
                                          "email",
                                          "telephone",
                                          "twitter_handle"])
companies_df.shape

(526, 28)

In [72]:
#companies_df.bibtex_key.compare(companies_df.company_name)
#remove bibtex_key as it is the same as company name
companies_df = companies_df.drop(columns=["bibtex_key"])

In [73]:
#remove ceo2 as it contains only one entry
#remove second hq as it is redundant, only three companies have this info
#remove news as its not really usable information
#remove csr - corporate social responsibility, not really important as its just the url
#remove company_number as it wont really help me
#remove company documents, not helpful in any way
#remove other known trading names, very limited data and unsure how to integrate into analysis
companies_df = companies_df.drop(columns=["ceo2",
                                          "address_2",
                                          "hq_2_city",
                                          "hq_2_country",
                                          "news",
                                          "csr",
                                          "company_number",
                                          "company_documents",
                                          "other_known_trading_names"])

In [74]:
print(companies_df.columns.values)

['company_name' 'hq_city' 'offices_in' 'technology_sold' 'description'
 'company_sales' 'incorporation_date' 'ceo' 'defense_contractor' 'eu'
 'founder' 'hq_country' 'nato' 'oecd' 'wassenaar' 'found_in'
 'parent_company' 'public_private']

In [75]:
companies_df.head(3)

,company_name,hq_city,offices_in,technology_sold,description,company_sales,incorporation_date,ceo,defense_contractor,eu,founder,hq_country,nato,oecd,wassenaar,found_in,parent_company,public_private
0,Varus Tecnologia,[Puebla],[Mexico],"[Phone Monitoring, Internet Monitoring, and In...","Varus Tecnologia makes Phone Monitoring, Inter...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Magor Corp,[Ottawa],[Canada],"[Analysis, Monitoring Centre]",Magor Corp makes Analysis and Monitoring Centr...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Reach-U,[Tartu],[Estonia],[Location Monitoring],Reach-U makes Location Monitoring technology. ...,[],1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
companies_df.company_name.duplicated().unique()

array([False])

In [77]:
#remove list type
companies_df.hq_city = companies_df.hq_city.fillna("")
for row in range(len(companies_df.hq_city)):
    companies_df.hq_city.iloc[row] = ''.join(companies_df.hq_city.iloc[row])

In [78]:
#rename confusing names
companies_df.hq_city.iloc[22] = "Cantu"
companies_df.hq_city.iloc[40] = "Gothenburg"
companies_df.hq_city.iloc[48] = "Saint-Etienne-de-Saint-Geoirs"
companies_df.hq_city.iloc[85] = "Saint-Gely-du-Fesc"
companies_df.hq_city.iloc[94] = "Le Kremlin-Bicetre"
companies_df.hq_city.iloc[105] = "Friedberg"
companies_df.hq_city.iloc[106] = "Buffalo"
companies_df.hq_city.iloc[108] = "Rochester"
companies_df.hq_city.iloc[115] = "Cambridge"
companies_df.hq_city.iloc[127] = "Neustadt an der Weinstrasse"
companies_df.hq_city.iloc[132] = "Bethesda"
companies_df.hq_city.iloc[144] = "Soeborg"
companies_df.hq_city.iloc[145] = "Chicago"
companies_df.hq_city.iloc[148] = "Lulea"
companies_df.hq_city.iloc[150] = "Santa Clara"
companies_df.hq_city.iloc[152] = "Zurich"
companies_df.hq_city.iloc[156] = "Philadelphia"
companies_df.hq_city.iloc[175] = "Alexandria"
companies_df.hq_city.iloc[245] = "San Jose"
companies_df.hq_city.iloc[246] = "Pasadena"
companies_df.hq_city.iloc[254] = "San Diego"
companies_df.hq_city.iloc[259] = "Reston"
companies_df.hq_city.iloc[262] = "Austin"
companies_df.hq_city.iloc[268] = "Brewster"
companies_df.hq_city.iloc[273] = "Metuchen"
companies_df.hq_city.iloc[287] = "Oakland"
companies_df.hq_city.iloc[314] = "San Jose"
companies_df.hq_city.iloc[325] = "Sunnyvale"
companies_df.hq_city.iloc[341] = "Milpitas"
companies_df.hq_city.iloc[359] = "Hayward"
companies_df.hq_city.iloc[369] = "Hayward"
companies_df.hq_city.iloc[389] = "Palo Alto"
companies_df.hq_city.iloc[396] = "Germantown"
companies_df.hq_city.iloc[414] = "Santa Clara"
companies_df.hq_city.iloc[416] = "Guelph"
companies_df.hq_city.iloc[423] = "Princeton"
companies_df.hq_city.iloc[506] = "Ra'anana"

In [122]:
from geopy import geocoders  
gn = geocoders.GeoNames(username="sebasg")

#extract latitude and longitude from output
hq_latitude = []
hq_longitude = []

for hq_city in companies_df.hq_city: 
    try:
        hq_city = gn.geocode(hq_city, exactly_one=False)[0]
        hq_latitude_val = hq_city.latitude
        hq_longitude_val = hq_city.longitude
    except TypeError:
        hq_latitude_val = np.nan
        hq_longitude_val = np.nan

    hq_latitude.append(hq_latitude_val)
    hq_longitude.append(hq_longitude_val)

In [125]:
#make new series in dataframe
companies_df["hq_latitude"] = hq_latitude
companies_df["hq_longitude"] = hq_longitude

In [164]:
#check if any hq
companies_df[companies_df.hq_latitude.isna() == True]

,company_name,hq_city,offices_in,technology_sold,description,company_sales,incorporation_date,ceo,defense_contractor,eu,founder,hq_country,nato,oecd,wassenaar,found_in,parent_company,public_private,hq_latitude,hq_longitude
106,Garland Technology,BuffaloNew York,[United States of America],[Internet Monitoring],Garland Technology makes Internet Monitoring t...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,Fiberblaze,Soeborg,[Denmark],[Internet Monitoring],Fiberblaze makes Internet Monitoring technolog...,[],2008,NaN,[0],[1],NaN,[Denmark],[1],[1],[1],NaN,NaN,NaN,NaN,NaN
160,Wirex,Yahud Monoson,[Israel],[Internet Monitoring],Wirex makes Internet Monitoring technology. Th...,[],2010,Tomer Saban,[0],[0],"Tomer Saban, Gilboa Davara, Vadim Lipovetsky",[Israel],[0],[1],[0],NaN,NaN,NaN,NaN,NaN
231,Terrogence,Bney Zion,[Israel],[Internet Monitoring],Terrogence makes Internet Monitoring technolog...,[],2004,Gadi Aviran,[0],[0],Gadi Aviran,[Israel],[0],[1],[0],NaN,NaN,NaN,NaN,NaN
369,Glimmerglass,HaywardCA,[United States of America],[Internet Monitoring],Glimmerglass makes Internet Monitoring technol...,[],2000,Robert Lundy,[0],[0],NaN,[United States of America],[1],[1],[1],NaN,NaN,NaN,NaN,NaN
404,Napatech,Soeborg,[Denmark],[Internet Monitoring],Napatech makes Internet Monitoring technology....,[],2003,Henrik Brill Jensen,[0],[1],Jens Christophersen,[Denmark],[1],[1],[1],NaN,NaN,NaN,NaN,NaN

In [207]:
#export for use in flask
companies_df.to_csv("Flask Surveillance Website/companies_df.csv",index=False)

Now calculate closest hq to a user given location

In [208]:
def closest_surveillance_company(user_input_name):

    list_of_coords = list(zip(companies_df.hq_latitude, companies_df.hq_longitude))
    user_city = gn.geocode(user_input_name, exactly_one=False)[0]
    user_city_coord = (user_city.latitude, user_city.longitude)

    distance_dict = dict()

    for position,coord in enumerate(list_of_coords):
        try:
            coord_distance = geopy.distance.distance(user_city_coord, coord).km
            distance_dict[position] = coord_distance
        except ValueError:
            pass
    
    index_lowest = min(distance_dict, key=distance_dict.get)
    entry = companies_df.iloc[index_lowest]
    return entry.company_name

In [209]:
#get min distance location
closest_surveillance_company("London")

'Silver Bullets'

In [195]:
materials_df

,bibtex_key,bibtex_type,category,company_name,date_added,date_modified,doc_cloud_id,document_title,found_in,hardware_software,...,support_or_customer_service,training,document_mentions,author,documen_title,bdsk_url_1,spy_files_release_volume,doc_cloud_container,parent_product,type_of_material
0,SAS-Institute-Inc_Customer-Success-Stories_Pro...,Document,"[Counter-Surveillance, Monitoring Centre, Anal...",SAS Institute Inc,[2014-07-08 12:15:57 +0000],[2014-07-08 12:20:22 +0000],[1215575-1290-sas-institue-inc-product-descrip...,[Customer Success Stories],"[United Kingdom, United States of America, Sou...",[Hardware/Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Oxygen-Forensics_Oxygen-Forensic-Suite_Brochure,Document,[Analysis],Oxygen Forensics,[2014-07-08 12:12:55 +0000],[2014-07-08 12:14:42 +0000],[1215576-1291-oxygen-forensics-brochure-oxygen...,[Oxygen Forensic Suite 2013],NaN,[Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Oxygen-Forensics_Oxygen-Forensic-Suite_Brochur...,Document,[Analysis],Oxygen Forensics,[2014-07-08 12:08:59 +0000],[2014-07-08 12:15:25 +0000],[1215591-1292-oxygen-forensics-brochure-oxygen...,[Oxygen Forensic Suite 2013],NaN,[Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CRFS_Spectrum-Intelligence-Systems_Product-Des...,Document,"[Location Monitoring, Monitoring Centre]",CRFS,[2014-07-08 12:06:13 +0000],[2014-07-08 12:08:23 +0000],[1215594-1293-crfs-product-description-spectrum],[Spectrum Intelligence Systems],NaN,[Hardware/Software],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CRFS_RFeye-Arrays_Product-Description,Document,[Location Monitoring],CRFS,[2014-07-08 12:03:59 +0000],[2014-07-09 20:10:09 +0000],[1214699-1295-crfs-product-description-product...,[RFeye Array],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,Altron_AKOR-3_Brochure-Specifications,Document,[Counter-Surveillance],Altron,[2013-05-15 10:02:51 +0000],[2013-08-07 12:05:53 +0000],[815759-35-altron-brochure-specifications-akor-3],NaN,NaN,[Both],...,[YES],NaN,NaN,NaN,NaN,[https://www.documentcloud.org/documents/81575...,[2],NaN,NaN,NaN
1355,Agnitio_SIFT-ASIS_Brochure,Document,[Biometrics],Agnitio,[2013-05-15 09:49:40 +0000],[2014-01-15 20:57:36 +0000],[409321-184-201106-iss-agnitio],NaN,NaN,[Software],...,NaN,NaN,NaN,NaN,NaN,[https://s3.amazonaws.com/s3.documentcloud.org...,[2],NaN,[BS-Cubed],NaN
1356,Agnitio_ASIS-BS-BATVOX_Currently-deployed-fiel...,Document,[Biometrics],Agnitio,[2013-05-14 17:05:13 +0000],[2014-04-01 14:46:55 +0000],[409135-20-200810-iss-prg-agnitio],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[https://s3.amazonaws.com/s3.documentcloud.org...,[2],NaN,NaN,NaN
1357,Acme-Packet_VoIP-security--myths-and-realities...,Document,[Internet Monitoring],Acme Packet,[2013-05-14 16:49:33 +0000],[2013-10-01 10:15:26 +0000],[409113-1-200702-iss-dxb-acme],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[https://s3.amazonaws.com/s3.documentcloud.org...,[2],NaN,NaN,NaN
1358,Ability_3G-CAT_Brochure-Specifications,Document,[Phone Monitoring],Ability,[2013-05-14 16:34:26 +0000],[2014-05-27 17:01:21 +0000],[815758-3-ability-brochure-specifications-3g-cat],NaN,NaN,[Hardware],...,NaN,NaN,NaN,NaN,NaN,[https://www.documentcloud.org/documents/81575...,[2],NaN,[IBIS-II],NaN